### PR TITLE
Remove sqlalchemy code

### PR DESCRIPTION
**Pull request by teddygroves**
This change removes all sqlalchemy code from the repository and flattens the folder structure accordingly: all files that were previously in `src/opentecr/data` now live in `src/opentecr_data_model`

### CODE REVIEW

**Comment by Midnighter** [comment]
I wonder if the ORM code should be left on another branch so it could easily be brought back to life?

I must admit I'm not a huge fan of a package name `opentecr_data_model`. My personal preference would be

```py
from opentecr.domain.model import CuratedMeasurement
```

but `opentecr.data.model` or `opentecr.model` are good alternatives IMHO.

**Comment by teddygroves** [comment]
> I wonder if the ORM could should be left on another branch so it could easily be brought back to life?
> 

Good idea, I'll make another PR.

> I must admit I'm not a huge fan of a package name `opentecr_data_model`. My personal preference would be
> 
> ```python
> from opentecr.domain.model import CuratedMeasurement
> ```
> 
> but `opentecr.data.model` or `opentecr.model` are good alternatives IMHO.

Yeah it's definitely an awkward name! I was thinking about avoiding a possible namespace conflict due to having multiple packages called `opentecr`. If you don't think this is~~n't~~ a big issue then I'm happy with any of those options. Just to add one more option to the hat, I see that equilibrator uses the convention that a repository `equilibrator-x` contains a package called `equilibrator_x`: maybe `opentecr_schema` would work here?

**Comment by teddygroves** [comment]
> Good idea, I'll make another PR.

Hmm actually I can't make PR's that suggest adding branches: I guess adding an orm branch is a job for an `opentecr/opentecr-schema` admin.

**Comment by Midnighter** [comment]
> Yeah it's definitely an awkward name! I was thinking about avoiding a possible namespace conflict due to having multiple packages called opentecr. If you don't think this isn't a big issue then I'm happy with any of those options. Just to add one more option to the hat, I see that equilibrator uses the convention that a repository equilibrator-x contains a package called equilibrator_x: maybe opentecr_schema would work here?

Good points. I see two options:

1. I think the schema would be the main part of a "client" package to interact with the database. So it could be okay to stick to `opentecr` and then name other packages differently.
2. Another option is to use [namespace packages](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/). So that this project installs itself as `opentecr.schema` and another package can install itself as `opentecr.data`, for example.

**Comment by teddygroves** [comment]
I guess the "you aren't going to need it" principle points towards just sticking with `opentecr` as per your point 1. 

This this change is a bit hard to keep in sync with #6 I think it's best to now close and make a new downstream pr.

**Pull request closed without merging**
